### PR TITLE
Use RSC and introduce global styles

### PR DESCRIPTION
**Pull request by refactornator**

### CODE REVIEW

**Review by wmalik-mux — APPROVED** [review]
LGTM! Nice to see that we could convert the list completely to a server component.

**Review by decepulis — COMMENTED** [review]
This looks good to me! Ready to merge as is.

That being said... and maybe this is too extra... I had a thought. We could, if we really wanted to, make `/upload/` a server-side component. Instead of using `router.push` on `handleSubmit`, I _think_ we could use native html form submit actions to achieve a similar effect. 

This would neatly remove lines 8-16 and lean into the whole "use the platform" thing that's been going around Remix and Svelte lately.

I don't have the exact syntax off the top of my head, but I'll be back from a haircut soon to try it out!

**Comment by decepulis** [comment]
Oh snap that comment was on the wrong PR 🤦

**Comment by refactornator** [comment]
> Oh snap that comment was on the wrong PR 🤦

@decepulis no worries! That makes more sense now 😁

**Pull request merged**
